name: py37cmp-gui

channels:
- aramislab
- anaconda
- conda-forge
- conda-forge/label/cf201901
- defaults

dependencies:
- python=3.7
- pip=20.1.1
- numpy=1.18.5 # =1.15.4
- matplotlib=3.2.2 # =2.2.3
- traits=6.0.0 # =5.1
- traitsui=6.1.3 # =6.0.0
- graphviz=2.40.1 # =2.40.1
- nipype=1.5.0 # =1.5.0
- git-annex=8.20210127 # =7.20190219
- pyside2=5.9.0a1 # =5.9.0a1
- fslpy=3.2.1 # =1.13.2
- fsleyes=0.33.0 # =0.27.3
- indexed_gzip=1.2.* # requirements of fsleyes

- pip:
    #- cfflib==2.0.5
    # - git+https://github.com/LTS5/cfflib.git
    - duecredit==0.8.0 # ==0.7.0
    - dipy==1.1.1 # ==0.15.0
    - mne==0.20.7 # ==0.17.1
    - obspy==1.2.1 # ==1.1.1
    - datalad[full]==0.14.0 # ==0.11.4
    - datalad-container==1.1.2
    - datalad-neuroimaging==0.3.1
    - pybids==0.10.2 # ==0.9.5
    - apptools==4.5.0
    - statsmodels==0.11.1 # ==0.9.0
    - networkx==2.2
    - sphinx==3.1.1 # ==1.8.5
    - sphinx_rtd_theme==0.5.0 # ==0.4.3
    - sphinx-argparse==0.2.5 # ==0.2.5
    - recommonmark==0.6.0 # ==0.5.0
    - pydicom==2.0.0 # ==1.4.2
