name: py27-test

channels:
- conda-forge
- aramislab
- defaults

dependencies:
- python=2.7.15
- pip=19.0.3
- numpy=1.15.4
- matplotlib=2.2.3
- networkx=2.2
- ants=2.2.0
- graphviz=2.38.0
- traits=4.6.0

- pip:
    - nipype==1.1.8
    - dipy==0.15.0
    - mne==0.17.1
    - obspy==1.1.1
    - datalad==0.11.3
    - datalad-revolution==0.6.0
    - datalad-container==0.2.1
    - datalad_neuroimaging==0.2.0
    - apptools==4.4.0
    - statsmodels==0.9.0
    - scipy==1.2.1
