name: py27cmp

channels:
- conda-forge
- defaults

dependencies:
- python=2.7.15
- pip=19.0.3
- numpy=1.15.4
- matplotlib=2.2.3
- traitsui=6.0.0

- pip:
    - nipype==1.1.8
    - dipy==0.15.0
    - mne==0.17.1
    - obspy==1.1.1
    - nose==1.3.7
    - python-xmp-toolkit==2.0.1
    - datalad==0.11.3
    - datalad-revolution==0.6.0
    - datalad-container==0.2.1
    - datalad_neuroimaging==0.2.0
    - apptools==4.4.0
    - statsmodels==0.9.0
