name: py27cmp-gui

channels:
- aramislab
- anaconda
- conda-forge
- defaults

dependencies:
- python=2.7.15
- pip=19.0.3
- numpy=1.15.4
- matplotlib=2.2.3
- traits=5.1
- traitsui=6.0.0
- graphviz=2.40.1
- nipype=1.1.8
- git-annex=7.20190219
- pyside2=5.9.0a1

- pip:
    - cfflib==2.0.5
    - duecredit==0.7.0
    - dipy==0.15.0
    - mne==0.17.1
    - obspy==1.1.1
    - datalad[full]==0.11.4
    - datalad-revolution==0.6.0
    - datalad-container==0.3.1
    - datalad_neuroimaging==0.2.0
    - pybids==0.9.1
    - apptools==4.4.0
    - statsmodels==0.9.0
    - networkx==2.2
    - sphinx==1.8.5
    - sphinx_rtd_theme==0.4.3
    - sphinx-argparse==0.2.5
    - recommonmark==0.5.0
