version: 2
jobs:
  build:
    environment:
      TZ: "/usr/share/zoneinfo/Europe/Zurich"
      SCRATCH: "/scratch"
    docker:
      - image: docker:18.01.0-ce-git
    working_directory: tmp/src/connectomemapper3
    steps:
      - run:
          name: Install parallel gzip and python2
          command: |
            apk add --no-cache pigz python2
      - restore_cache:
          keys:
            - docker-{{ .Branch }}-{{ epoch }}
            - docker-{{ .Branch }}-
            - docker-master-
            - docker-
          paths:
            - /tmp/cache/docker.tar.gz
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Load Docker image layer cache
          no_output_timeout: 30m
          command: |
            docker info
            set +o pipefail
            if [ -f /tmp/cache/docker.tar.gz ]; then
              pigz -d --stdout /tmp/cache/docker.tar.gz | docker load
              docker images
            fi
      - run:
          name: Build Docker image
          no_output_timeout: 60m
          command: |
            # Get version, update files.
            THISVERSION=$( python get_version.py )
            echo "THISVERSION : ${THISVERSION}"
            echo "CIRCLE_TAG : ${CIRCLE_TAG}"
            if [[ ${THISVERSION:0:1} == "0" ]] ; then
              echo "WARNING: latest git tag could not be found"
              echo "Please, make sure you fetch all tags from upstream with"
              echo "the command ``git fetch --tags --verbose`` and push"
              echo "them to your fork with ``git push origin --tags``"
            fi
            # Build docker image
            e=1 && for i in {1..5}; do
              docker build \
                --cache-from=sebastientourbier/connectomemapper-bidsapp \
                --rm=false \
                -t sebastientourbier/connectomemapper-bidsapp:latest \
                --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
                --build-arg VCS_REF=`git rev-parse --short HEAD` \
                --build-arg VERSION="${CIRCLE_TAG:-$THISVERSION}" . \
              && e=0 && break || sleep 15
            done && [ "$e" -eq "0" ]
      - run:
          name: Save Docker Images
          no_output_timeout: 40m
          command: |
            mkdir -p /tmp/cache
            docker save sebastientourbier/connectomemapper-ubuntu16.04:latest sebastientourbier/connectomemapper-bidsapp:latest \
            | pigz -8 -p 3 > /tmp/cache/docker.tar.gz
      - persist_to_workspace:
          root: /tmp
          paths:
            - cache/docker.tar.gz
            - src/connectomemapper-bidsapp

  get_data:
    machine:
      # Ubuntu 14.04 with Docker 17.10.0-ce
      image: circleci/classic:201711-01
    working_directory: /home/circleci/data
    steps:
      - restore_cache:
          keys:
            - data-{{ epoch }}
            - data-
      - run:
          name: Get test data from ds000005
          command: |
            mkdir -p /tmp/data
            if [[ ! -d /tmp/data/ds005 ]]; then
              wget --retry-connrefused --waitretry=5 --read-timeout=20 --timeout=15 -t 0 -q \
                -O ds005_downsampled.tar.gz "https://files.osf.io/v1/resources/fvuh8/providers/osfstorage/57f32a429ad5a101f977eb75"
              tar xvzf ds005_downsampled.tar.gz -C /tmp/data/
            else
              echo "Dataset ds000005 was cached"
            fi
      - run:
          name: Get FreeSurfer derivatives for ds000005
          command: |
            if [[ ! -d /tmp/ds005/derivatives/freesurfer ]]; then
              mkdir -p /tmp/ds005/derivatives
              wget --retry-connrefused --waitretry=5 --read-timeout=20 --timeout=15 -t 0 -q \
                -O ds005_derivatives_freesurfer.tar.gz "https://files.osf.io/v1/resources/fvuh8/providers/osfstorage/58fe59eb594d900250960180"
              tar xvzf ds005_derivatives_freesurfer.tar.gz -C /tmp/ds005/derivatives
            else
              echo "FreeSurfer derivatives of ds000005 were cached"
            fi
      - run:
          name: Store FreeSurfer license file
          command: |
            mkdir -p /tmp/fslicense
            cd /tmp/fslicense
            echo `echo c2ViYXN0aWVuLnRvdXJiaWVyMUBnbWFpbC5jb20KMzAwNzYKICpDYUpVZ0VMQlJEYkEKIEZTMkkyWDNwNkpicWcK== | base64 -di` > /tmp/fslicense/license.txt
      - persist_to_workspace:
          root: /tmp
          paths:
            - data
            - fslicense
            - ds005/derivatives/freesurfer
      - save_cache:
         key: data-{{ epoch }}
         paths:
            - /tmp/data
            - /tmp/ds005/derivatives/freesurfer

  # update_cache:
  #   machine:
  #     # Ubuntu 14.04 with Docker 17.10.0-ce
  #     image: circleci/classic:201711-01
  #   working_directory: /tmp/src/multiscalebrainparcellator
  #   steps:
  #     - attach_workspace:
  #         at: /tmp
  #     - save_cache:
  #        key: docker-{{ .Branch }}-{{ epoch }}
  #        paths:
  #          - /tmp/cache/docker.tar.gz

  test:
    machine:
      # Ubuntu 14.04 with Docker 17.10.0-ce
      image: circleci/classic:201711-01
    working_directory: /tmp/ds005
    environment:
      - FS_LICENSE: /tmp/fslicense/license.txt
    steps:
      - checkout:
          path: /home/circleci/src/connectomemapper-bidsapp
      - run:
          name: Check whether build should be skipped
          command: |
            cd /home/circleci/src/connectomemapper-bidsapp
            if [[ "$( git log --format=oneline -n 1 $CIRCLE_SHA1 | grep -i -E '\[skip[ _]?ds005\]' )" != "" ]]; then
              echo "Skipping ds000005 build"
              circleci step halt
            fi
      - attach_workspace:
          at: /tmp
      - restore_cache:
          keys:
            - ds005-anat-v12-{{ .Branch }}-{{ epoch }}
            - ds005-anat-v12-{{ .Branch }}
            - ds005-anat-v12-master
            - ds005-anat-v12-
      - run:
          name: Load Docker image layer cache
          no_output_timeout: 30m
          command: |
            docker info
            set +o pipefail
            if [ -f /tmp/cache/docker.tar.gz ]; then
              sudo apt update && sudo apt -y install pigz
              pigz -d --stdout /tmp/cache/docker.tar.gz | docker load
              docker images
            fi
      - run:
          name: Run anatomical workflow on ds005
          no_output_timeout: 4h
          command: |
            mkdir -p /tmp/ds005/work /tmp/ds005/derivatives
            rm -R /tmp/ds005/derivatives/cmp/sub-01/tmp/anatomical_pipeline/parcellation_stage/Lausanne2018_parcellation
            docker run -it --rm \
                -v /tmp/data/ds005:/tmp \
                -v /home/circleci/src/connectomemapper-bidsapp/config:/tmp/code \
                -v $FS_LICENSE:/opt/freesurfer/license.txt \
                sebastientourbier/connectomemapper-bidsapp:latest \
                /tmp /tmp/derivatives participant --participant_label 01 \
                --anat_pipeline_config /tmp/code/ref_anatomical_config.ini

      - save_cache:
         key: ds005-anat-v12-{{ .Branch }}-{{ epoch }}
         paths:
            - /tmp/ds005/work
            - /tmp/ds005/derivatives/cmp
      - run:
          name: Checking outputs of Connectome Mapper run (anatomical pipeline only)
          command: |
            mkdir -p /tmp/ds005/test
            find /tmp/ds005/derivatives/cmp -path */figures -prune -o -name "*" -print | sed s+/tmp/ds005/derivatives/++ | sort > /tmp/ds005/test/outputs.out
            exit $?
      - run:
          name: Clean working directory
          when: always
          command: |
            sudo chown $(id -un):$(id -gn) -R /tmp/ds005
            find /tmp/ds005/work -not -name "*.svg" -not -name "*.html" -not -name "*.rst" \
                -not -name "*.mat" -not -name "*.gpickle" -not -name "*.lta" -not -name "*.json" -not -name "*.txt" -not -name "*.pklz" -type f -delete
      - store_artifacts:
          path: /tmp/ds005/test
      - store_artifacts:
          path: /tmp/ds005/derivatives/cmp

  deploy_docker:
    machine:
      # Ubuntu 14.04 with Docker 17.10.0-ce
      image: circleci/classic:201711-01
    working_directory: /tmp/src/connectomemapper-bidsapp
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: Load Docker image layer cache
          no_output_timeout: 30m
          command: |
            docker info
            set +o pipefail
            if [ -f /tmp/cache/docker.tar.gz ]; then
              sudo apt update && sudo apt -y install pigz
              pigz -d --stdout /tmp/cache/docker.tar.gz | docker load
              docker images
            fi
      - run:
          name: Deploy to Docker Hub
          no_output_timeout: 40m
          command: |
            if [[ -n "$DOCKER_PASS" ]]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker tag sebastientourbier/connectomemapper-bidsapp sebastientourbier/connectomemapper-bidsapp:unstable
              docker push sebastientourbier/connectomemapper-bidsapp:unstable
              if [[ -n "$CIRCLE_TAG" ]]; then
                docker push sebastientourbier/connectomemapper-bidsapp:latest
                docker tag sebastientourbier/connectomemapper-bidsapp sebastientourbier/connectomemapper-bidsapp:$CIRCLE_TAG
                docker push sebastientourbier/connectomemapper-bidsapp:$CIRCLE_TAG
              fi
            fi

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/

      - get_data:
          filters:
            branches:
              ignore:
                - /docs?\/.*/
            tags:
              only: /.*/

      # - build_docs:
      #     requires:
      #       - build
      #     filters:
      #       branches:
      #         ignore:
      #           - /ds005\/.*/
      #       tags:
      #         only: /.*/

      # - update_cache:
      #     requires:
      #       - build
      #     filters:
      #       branches:
      #         ignore:
      #           - /docs?\/.*/
      #       tags:
      #         only: /.*/

      - test:
          requires:
            - get_data
            # - update_cache
            - build
          filters:
            branches:
              ignore:
                - /docs?\/.*/
            tags:
              only: /.*/

      - deploy_docker:
          requires:
            - build
            # - build_docs
            - test
          filters:
            # ignore any commit on any branch by default
            branches:
              ignore: /.*/
              # only: master
            # only act on version tags
            tags:
              only: /^v.*/
