name: py37cmp-gui

channels:
- conda-forge
- aramislab
- mrtrix3

dependencies:
- python=3.7
- pip=20.1.1
- numpy=1.19.2
- matplotlib=3.2.2  # 2.2.3
- graphviz=2.40.1
- traits=6.2.0
- traitsui=7.0.0
- configparser=5.0.0
- nipype=1.5.1
- pyside2=5.9.0a1
- pydotplus=2.0.2
- fslpy=3.2.1 # =1.13.2
- fsleyes=0.33.0 # =0.27.3
- indexed_gzip=1.2.0 # requirements of fsleyes
- dipy=1.3.0
- cvxpy-base=1.1.7
- cvxpy=1.1.7
- obspy=1.2.2
- mrtrix3=3.0.2

- pip:
    - duecredit==0.8.0  # 0.7.0
    - mne==0.20.7  # 0.17.1
    - datalad[full]==0.14.0  # 0.11.3
    - datalad-container==1.1.2
    - datalad_neuroimaging==0.3.1
    - pybids==0.10.2  # 0.9.1
    - statsmodels==0.11.1  # 0.9.0
    - networkx==2.4
    - pydicom==2.0.0  # 1.4.2
