name: py27cmp-core

channels:
- anaconda
- conda-forge
- aramislab
- defaults

dependencies:
- python=2.7.15
- pip=19.0.3
- ants=2.2.0
- numpy=1.15.4
- matplotlib=2.2.3
- graphviz=2.40.1
- nipype=1.1.8
- git-annex=7.20190219

- pip:
    - duecredit==0.7.0
    - dipy==0.15.0
    - mne==0.17.1
    - obspy==1.1.1
    - datalad[full]==0.11.3
    - datalad-revolution==0.6.0
    - datalad-container==0.2.1
    - datalad_neuroimaging==0.2.0
    - apptools==4.4.0
    - statsmodels==0.9.0
    - networkx==2.2
