name: py36cmp-core

channels:
- anaconda
- conda-forge
- aramislab
- defaults

dependencies:
- python=3.6
- pip=20.1.1
- ants=2.2.0
- numpy=1.15.4
- matplotlib=2.2.3
- graphviz=2.40.1
- traits=5.1.1
- nipype=1.5.0
- pyside2=5.9.0a1
- vtk=7.0.0
- git-annex=7.20190219

- pip:
    # - git+https://github.com/LTS5/cfflib.git
    - duecredit==0.7.0
    - dipy==0.15.0
    - mne==0.17.1
    - obspy==1.1.1
    - datalad[full]==0.11.3
    - datalad-revolution==0.6.0
    - datalad-container==0.3.1
    - datalad_neuroimaging==0.2.0
    - pybids==0.9.5
    - apptools==4.5.0
    - statsmodels==0.9.0
    - networkx==2.2
    - sphinx==1.5.1
    - sphinx_rtd_theme==0.4.3
    - sphinx-argparse==0.2.5
    - recommonmark==0.5.0
    - fury==0.1.4
    - pydicom==1.4.2
